# build_windows.py
import os
import sys
import shutil
import subprocess
from pathlib import Path

def build_executable():
    """Build Windows executable using PyInstaller"""
    
    project_root = Path(__file__).parent
    src_dir = project_root / "src"
    build_dir = project_root / "build"
    dist_dir = project_root / "dist"
    
    # Clean previous builds
    if build_dir.exists():
        shutil.rmtree(build_dir)
    if dist_dir.exists():
        shutil.rmtree(dist_dir)
    
    # Create necessary directories
    (project_root / "output").mkdir(exist_ok=True)
    
    # PyInstaller command
    pyinstaller_cmd = [
        "pyinstaller",
        "--name=DTF Halftoner Pro",
        "--windowed",  # No console window
        "--onefile",   # Single executable
        "--icon=resources/icons/app_icon.ico",
        "--add-data=resources;resources",
        "--add-data=docs;docs",
        "--add-data=README.md;.",
        "--noconfirm",  # Replace output directory without confirmation
        "--clean",      # Clean PyInstaller cache
        "--paths=src",
        "src/main.py"
    ]
    
    print("Building executable...")
    print("Command:", " ".join(pyinstaller_cmd))
    
    # Run PyInstaller
    result = subprocess.run(pyinstaller_cmd, capture_output=True, text=True)
    
    if result.returncode != 0:
        print("Build failed!")
        print("STDOUT:", result.stdout)
        print("STDERR:", result.stderr)
        return False
    
    print("Build successful!")
    
    # Copy additional resources
    print("Copying resources...")
    
    # Create distribution package
    dist_package = project_root / "DTF_Halftoner_Pro"
    if dist_package.exists():
        shutil.rmtree(dist_package)
    
    # Copy executable
    exe_source = dist_dir / "DTF Halftoner Pro.exe"
    if exe_source.exists():
        dist_package.mkdir()
        shutil.copy(exe_source, dist_package / "DTF Halftoner Pro.exe")
        
        # Copy resources
        shutil.copytree(
            project_root / "resources",
            dist_package / "resources",
            dirs_exist_ok=True
        )
        
        # Copy docs
        if (project_root / "docs").exists():
            shutil.copytree(
                project_root / "docs",
                dist_package / "docs",
                dirs_exist_ok=True
            )
        
        # Copy sample images
        samples_dir = project_root / "sample_images"
        if samples_dir.exists():
            shutil.copytree(
                samples_dir,
                dist_package / "sample_images",
                dirs_exist_ok=True
            )
        
        # Create README
        with open(dist_package / "README.txt", "w") as f:
            f.write("DTF Halftoner Pro\n")
            f.write("=================\n\n")
            f.write("Professional DTF halftoning software.\n\n")
            f.write("Usage:\n")
            f.write("1. Run 'DTF Halftoner Pro.exe'\n")
            f.write("2. Load an image\n")
            f.write("3. Adjust settings\n")
            f.write("4. Click 'Process'\n")
            f.write("5. Save results\n")
        
        print(f"Package created at: {dist_package}")
        return True
    
    return False

def create_installer():
    """Create Windows installer using Inno Setup"""
    
    project_root = Path(__file__).parent
    dist_package = project_root / "DTF_Halftoner_Pro"
    
    if not dist_package.exists():
        print("Distribution package not found. Build executable first.")
        return False
    
    # Create Inno Setup script
    iss_content = f"""; DTF Halftoner Pro Installer Script
; Generated by build script

#define MyAppName "DTF Halftoner Pro"
#define MyAppVersion "1.0"
#define MyAppPublisher "DTF Tools"
#define MyAppURL "https://example.com"
#define MyAppExeName "DTF Halftoner Pro.exe"

[Setup]
AppId={{{{D3A8F4B1-9C6E-4A7D-88F2-1C5E9A3B8D7F}}}}
AppName={{#MyAppName}}
AppVersion={{#MyAppVersion}}
AppPublisher={{#MyAppPublisher}}
AppPublisherURL={{#MyAppURL}}
AppSupportURL={{#MyAppURL}}
AppUpdatesURL={{#MyAppURL}}
DefaultDirName={{autopf}}\{{#MyAppName}}
DefaultGroupName={{#MyAppName}}
AllowNoIcons=yes
LicenseFile={project_root}\LICENSE.txt
OutputDir={project_root}\installer
OutputBaseFilename=DTF_Halftoner_Pro_Setup
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{{cm:CreateDesktopIcon}}"; GroupDescription: "{{cm:AdditionalIcons}}"; Flags: unchecked

[Files]
Source: "{dist_package}\{{#MyAppExeName}}"; DestDir: "{{app}}"; Flags: ignoreversion
Source: "{dist_package}\resources\*"; DestDir: "{{app}}\resources"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{dist_package}\docs\*"; DestDir: "{{app}}\docs"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{dist_package}\sample_images\*"; DestDir: "{{app}}\sample_images"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{dist_package}\README.txt"; DestDir: "{{app}}"; Flags: ignoreversion

[Icons]
Name: "{{group}}\{{#MyAppName}}"; Filename: "{{app}}\{{#MyAppExeName}}"
Name: "{{group}}\{{cm:UninstallProgram,{{#MyAppName}}}}"; Filename: "{{uninstallexe}}"
Name: "{{commondesktop}}\{{#MyAppName}}"; Filename: "{{app}}\{{#MyAppExeName}}"; Tasks: desktopicon

[Run]
Filename: "{{app}}\{{#MyAppExeName}}"; Description: "{{cm:LaunchProgram,{{#StringChange(MyAppName, '&', '&&')}}}}"; Flags: nowait postinstall skipifsilent

[UninstallDelete]
Type: filesandordirs; Name: "{{app}}"
"""
    
    # Write ISS file
    iss_path = project_root / "installer_script.iss"
    with open(iss_path, "w") as f:
        f.write(iss_content)
    
    # Check if Inno Setup is installed
    inno_paths = [
        r"C:\Program Files (x86)\Inno Setup 6\ISCC.exe",
        r"C:\Program Files\Inno Setup 6\ISCC.exe",
    ]
    
    inno_exe = None
    for path in inno_paths:
        if os.path.exists(path):
            inno_exe = path
            break
    
    if inno_exe is None:
        print("Inno Setup not found. Installer script created at:")
        print(iss_path)
        print("Please compile it using Inno Setup Compiler.")
        return False
    
    # Compile installer
    print("Creating installer...")
    result = subprocess.run([inno_exe, str(iss_path)], capture_output=True, text=True)
    
    if result.returncode == 0:
        print("Installer created successfully!")
        installer_path = project_root / "installer" / "DTF_Halftoner_Pro_Setup.exe"
        if installer_path.exists():
            print(f"Installer: {installer_path}")
        return True
    else:
        print("Installer creation failed!")
        print("STDOUT:", result.stdout)
        print("STDERR:", result.stderr)
        return False

if __name__ == "__main__":
    print("DTF Halftoner Pro - Build System")
    print("=" * 40)
    
    print("\n1. Building executable...")
    if build_executable():
        print("\n2. Creating installer...")
        create_installer()
    else:
        print("Build failed!")
    
    input("\nPress Enter to exit...")